# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DataFixtures/'

    App\Command\SamlImportMetadataCommand:
        arguments:
            $defaultUri: '%env(DEFAULT_URI)%'

    App\Service\EncryptionService:
        arguments:
            $encryptionKey: '%env(APP_ENCRYPTION_KEY)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - '%env(resolve:DATABASE_URL)%'
            - { db_table: 'sessions', db_id_col: 'sess_id', db_data_col: 'sess_data', db_time_col: 'sess_time', db_lifetime_col: 'sess_lifetime' }

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
        App\DataFixtures\:
            resource: '../src/DataFixtures/'

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
        App\DataFixtures\:
            resource: '../src/DataFixtures/'
